/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-leo
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LEO_API_H
#define INCLUDED_LEO_API_H

#include <gnuradio/attributes.h>
#include <string>

#ifdef gnuradio_leo_EXPORTS
#define LEO_API __GR_ATTR_EXPORT
#else
#define LEO_API __GR_ATTR_IMPORT
#endif

#ifndef GR_LEO_REL_DATA_PATH
#error "Path for data files must be defined"
#endif

/**
 * Speed of light in m/s
 */
#define LIGHT_SPEED                     299792458

/**
* Boltzman's constant dBW/KHz
*/
#define BOLTZMANS_CONST         -228.6

/**
* Ground station effective noise temperature in K
*/
#define GS_NOISE_TEMP         510

/**
 * Radius of the Earth in km
 */
#define EARTH_RADIUS         6356.766
#define MATH_PI              3.14159265358979323846

#endif /* INCLUDED_LEO_API_H */
