/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(antenna_pointing_loss.h)                                   */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/leo/antenna_pointing_loss.h>

void bind_antenna_pointing_loss(py::module& m)
{

    py::module m_antenna = m.def_submodule("attenuation");
    using antenna_pointing_loss = ::gr::leo::attenuation::antenna_pointing_loss;

    py::class_<antenna_pointing_loss, gr::leo::generic_attenuation,
               std::shared_ptr<antenna_pointing_loss>>(m_antenna, "antenna_pointing_loss")

        .def_static("make",
             &antenna_pointing_loss::make,
             py::arg("tracker_antenna"),
             py::arg("satellite_antenna"))

        ;
}
