/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(generic_model.h)                                         */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/leo/tracker.h>
#include <gnuradio/leo/generic_model.h>

void bind_generic_model(py::module& m)
{

    using generic_model = ::gr::leo::generic_model;

    py::class_<generic_model, std::shared_ptr<generic_model>>(m, "generic_model")

        .def("generic_work",
             &generic_model::generic_work,
             py::arg("inbuffer"),
             py::arg("outbuffer"),
             py::arg("noutput_items"),
             py::arg("samp_rate"))

        .def("advance_time",
             &generic_model::advance_time,
             py::arg("us"))

        .def("unique_id",
             &generic_model::unique_id)

        .def("alias",
             &generic_model::alias)
        
        .def("get_tracker",
             &generic_model::get_tracker)

        .def("get_frequency",
             &generic_model::get_frequency)

        .def("get_polarization",
             &generic_model::get_polarization)

        .def("get_satellite_antenna_gain",
             &generic_model::get_satellite_antenna_gain)

        .def("get_tx_power_dbm",
             &generic_model::get_tx_power_dbm)

        .def("get_receiver_bandwidth",
             &generic_model::get_receiver_bandwidth)

        .def("get_noise_temperature",
             &generic_model::get_noise_temperature)

        .def("get_noise_figure",
             &generic_model::get_noise_figure)

        .def("get_tracker_antenna",
             &generic_model::get_tracker_antenna)

        .def("get_satellite_antenna",
             &generic_model::get_satellite_antenna)

        .def("orbit_update",
             &generic_model::orbit_update)

        .def("get_csv_log",
             &generic_model::get_csv_log)
     
        .def("get_tags_vector",
             &generic_model::get_tags_vector)

        .def("get_noise_floor",
             &generic_model::get_noise_floor)

        .def("aos",
             &generic_model::aos)

        .def("estimate_link_margin",
             &generic_model::estimate_link_margin)

        .def("calculate_noise_floor",
             &generic_model::calculate_noise_floor)

        .def("get_doppler_freq",
             &generic_model::get_doppler_freq)

        ;

}
