/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(generic_attenuation.h)                                         */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/leo/satellite.h>
#include <gnuradio/leo/generic_attenuation.h>


void bind_generic_attenuation(py::module& m)
{

    using generic_attenuation = ::gr::leo::generic_attenuation;

    py::class_<generic_attenuation, std::shared_ptr<generic_attenuation>>(m, "generic_attenuation")

        .def_static("make",
             &generic_attenuation::make)

        .def_static("set_elevation_angle",
             &generic_attenuation::set_elevation_angle,
             py::arg("elev_angle"))

        .def_static("set_polarization",
             &generic_attenuation::set_polarization,
             py::arg("polar"))

        .def_static("set_slant_range",
             &generic_attenuation::set_slant_range,
             py::arg("range"))

        .def_static("set_frequency",
             &generic_attenuation::set_frequency,
             py::arg("freq"))

        .def("get_attenuation",
             &generic_attenuation::get_attenuation)

        ;

}
