/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(leo_model.h)                                   */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/leo/leo_model.h>

void bind_leo_model(py::module& m)
{

    py::module m_model = m.def_submodule("model");
    using leo_model = ::gr::leo::model::leo_model;

    py::class_<leo_model, gr::leo::generic_model,
               std::shared_ptr<leo_model>>(m_model, "leo_model")

        .def_static("make",
             &leo_model::make,
             py::arg("tracker"),
             py::arg("mode"),
             py::arg("fspl_attenuation_enum"),
             py::arg("pointing_attenuation_enum"),
             py::arg("doppler_shift_enum"),
             py::arg("atmo_gases_attenuation"),
             py::arg("precipitation_attenuation"),
             py::arg("enable_link_margin"),
             py::arg("surface_watervap_density") = 75,
             py::arg("temperature") = 0,
             py::arg("rainfall_rate") = 25)

        ;
}
