/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(precipitation_itu.h)                                   */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/leo/precipitation_itu.h>

void bind_precipitation_itu(py::module& m)
{

    py::module m_antenna = m.def_submodule("attenuation");
    using precipitation_itu = ::gr::leo::attenuation::precipitation_itu;

    py::class_<precipitation_itu, gr::leo::generic_attenuation,
               std::shared_ptr<precipitation_itu>>(m_antenna, "precipitation_itu")

        .def_static("make",
             &precipitation_itu::make,
             py::arg("rainfall_rate"),
             py::arg("tracker_longtitude"),
             py::arg("tracker_latitude"),
             py::arg("tracker_altitude"),
             py::arg("mode"))

        ;
}
