/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(satellite.h)                                         */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/leo/satellite.h>

void bind_satellite(py::module& m)
{

    using satellite = ::gr::leo::satellite;


    py::class_<satellite, std::shared_ptr<satellite>>(m, "satellite")

        .def_static("make",
             &satellite::make,
             py::arg("tle_title"),
             py::arg("tle_1"),
             py::arg("tle_2"),
             py::arg("comm_freq_tx"),
             py::arg("comm_freq_rx"),
             py::arg("tx_power_dbm"),
             py::arg("tx_antenna"),
             py::arg("rx_antenna"),
             py::arg("noise_figure"),
             py::arg("noise_temp"),
             py::arg("rx_bw"))

        .def("get_comm_freq_rx", &satellite::get_comm_freq_rx)

        .def("get_comm_freq_tx",
             &satellite::get_comm_freq_tx)

        .def("get_tle_1",
             &satellite::get_tle_1)

        .def("get_tle_2",
             &satellite::get_tle_2)
        
        .def("get_tle_title",
             &satellite::get_tle_title)

        .def("get_tx_antenna",
             &satellite::get_tx_antenna)

        .def("get_rx_antenna",
             &satellite::get_rx_antenna)

        .def("get_tx_power_dbm",
             &satellite::get_tx_power_dbm)

        .def("get_noise_figure",
             &satellite::get_noise_figure)

        .def("get_noise_temperature",
             &satellite::get_noise_temperature)

        .def("get_rx_bandwidth",
             &satellite::get_rx_bandwidth)
        ;

}
