/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-leo
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_LEO_API_H
#define INCLUDED_LEO_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_leo_EXPORTS
#  define LEO_API __GR_ATTR_EXPORT
#else
#  define LEO_API __GR_ATTR_IMPORT
#endif

/**
 * Speed of light in m/s
 */
#define LIGHT_SPEED                     299792458

enum atmo_gases_attenuation_t
{
  NONE = 0, ATMO_GASES_ITU, ATMO_GASES_REGRESSION
};

/**
 * Radius of the Earth in km
 */
#define EARTH_RADIUS         6356.766
#define MATH_PI              3.14159265358979323846

#endif /* INCLUDED_LEO_API_H */
