/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-leo
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <gnuradio/io_signature.h>
#include <leo/utils/datetime.h>
#include <iostream>
#include <chrono>
#include <ctime>

namespace gr
{
  namespace leo
  {

    datetime::datetime (const std::string& datetime) :
            d_UTC_format ("%Y-%m-%dT%H:%M:%S")
    {
      std::tm tm;

      strptime (datetime.c_str(), d_UTC_format.c_str (), &tm);
      std::chrono::system_clock::time_point tp =
          std::chrono::system_clock::from_time_t (std::mktime (&tm));

      std::time_t t = std::chrono::system_clock::to_time_t (tp);
      std::tm utc_tm = *localtime (&t);

      d_year = utc_tm.tm_year + 1900;
      d_month = utc_tm.tm_mon + 1;
      d_day = utc_tm.tm_mday;
      d_hour = utc_tm.tm_hour;
      d_minute = utc_tm.tm_min;
      d_second = utc_tm.tm_sec;
    }

    datetime::~datetime ()
    {
    }

    size_t
    datetime::get_day () const
    {
      return d_day;
    }

    size_t
    datetime::get_hour () const
    {
      return d_hour;
    }

    size_t
    datetime::get_month () const
    {
      return d_month;
    }

    size_t
    datetime::get_second () const
    {
      return d_second;
    }

    size_t
    datetime::get_year () const
    {
      return d_year;
    }

    size_t
    datetime::get_minute () const
    {
      return d_minute;
    }

  } /* namespace leo */
} /* namespace gr */
