/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-leo
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

#ifndef INCLUDED_LEO_UTILS_DATETIME_H
#define INCLUDED_LEO_UTILS_DATETIME_H

#include <leo/api.h>
#include <string>

namespace gr
{
  namespace leo
  {

    /*!
     * \brief <+description+>
     *
     */
    class LEO_API datetime
    {
    public:
      datetime (const std::string& datetime);

      ~datetime ();

      size_t
      get_day ();

      size_t
      get_hour ();

      size_t
      get_month ();

      size_t
      get_second ();

      size_t
      get_year ();

      size_t
      get_minute();

    private:

      std::string d_UTC_format;
      size_t d_year;
      size_t d_month;
      size_t d_day;
      size_t d_hour;
      size_t d_minute;
      size_t d_second;

    };

  } // namespace leo
} // namespace gr

#endif /* INCLUDED_LEO_UTILS_DATETIME_H */

